# Generated by Django 5.2.4 on 2025-07-27 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(verbose_name=200)),
                ('author', models.CharField(verbose_name=100)),
                ('publication_year', models.IntegerField()),
            ],
        ),
    ]
